# Generated by Django 5.0.1 on 2024-02-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
